// ESLint 9 flat config. Replaces .eslintrc.json + .eslintignore.

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import jsdoc from "eslint-plugin-jsdoc";
import prettier from "eslint-plugin-prettier";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";

// Foundry / dnd5e / module globals — read-only references.
const foundryGlobals = {
  Hooks: "readonly",
  game: "readonly",
  ui: "readonly",
  globalThis: "readonly",
  Handlebars: "readonly",
  Babele: "readonly",
  foundry: "readonly",
  CONFIG: "readonly",
  CONST: "readonly",
  canvas: "readonly",
  Roll: "readonly",
  libWrapper: "readonly",
  socketlib: "readonly",
  DatabaseBackend: "readonly",
  Actor: "readonly",
  Adventure: "readonly",
  Cards: "readonly",
  ChatMessage: "readonly",
  Combat: "readonly",
  Dice: "readonly",
  FogExploration: "readonly",
  Folder: "readonly",
  Item: "readonly",
  Journal: "readonly",
  JournalEntry: "readonly",
  Macro: "readonly",
  Playlist: "readonly",
  RollTable: "readonly",
  Scene: "readonly",
  Setting: "readonly",
  User: "readonly",
  dnd5e: "readonly",
  fromUuid: "readonly",
  fromUuidSync: "readonly",
  TokenDocument: "readonly",
  Canvas: "readonly",
  canvasTextStyle: "readonly",
  weatherEffects: "readonly",
  controlIcons: "readonly",
  fontDefinitions: "readonly",
  _fontFamilies: "readonly",
  defaultFontFamily: "readonly",
  statusEffects: "readonly",
  specialStatusEffects: "readonly",
  sounds: "readonly",
  supportedLanguages: "readonly",
  i18n: "readonly",
  time: "readonly",
  ActiveEffect: "readonly",
  ActorDelta: "readonly",
  Card: "readonly",
  TableResult: "readonly",
  JournalEntryPage: "readonly",
  PlaylistSound: "readonly",
  AmbientLight: "readonly",
  AmbientSound: "readonly",
  Combatant: "readonly",
  Drawing: "readonly",
  MeasuredTemplate: "readonly",
  Note: "readonly",
  Tile: "readonly",
  Token: "readonly",
  Wall: "readonly",
  TinyMCE: "readonly",
  TextEditor: "readonly",
  WebRTC: "readonly",
  DND5E: "readonly",
};

const sharedRules = {
  // Prettier owns formatting; this rule lets ESLint surface prettier diffs.
  "prettier/prettier": ["error", { endOfLine: "auto" }],

  // Real errors.
  eqeqeq: "error",
  "no-throw-literal": "error",
  "no-const-assign": "error",
  "no-this-before-super": "error",
  "constructor-super": "error",
  "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
  "no-unused-expressions": ["error", { allowShortCircuit: true }],

  // Style warnings (mostly logic / smell flags; prettier handles whitespace).
  "no-console": "off",
  "array-callback-return": "warn",
  "default-param-last": "warn",
  "no-empty": ["warn", { allowEmptyCatch: true }],
  "no-implicit-coercion": ["warn", { allow: ["!!"] }],
  "no-unsafe-negation": ["warn", { enforceForOrderingRelations: true }],
  "no-unsafe-optional-chaining": ["warn", { disallowArithmeticOperators: true }],
  "no-useless-computed-key": ["warn", { enforceForClassMembers: true }],
  "no-self-assign": "warn",
  "no-mixed-operators": "off",
  "no-var": "warn",
  "prefer-template": "warn",
  "dot-notation": "warn",
  "no-useless-escape": "warn",
  "no-extra-boolean-cast": ["warn", { enforceForLogicalOperands: true }],

  // typescript-eslint rules (apply to plain JS too, useful for forbidding any).
  "@typescript-eslint/no-explicit-any": "error",
  "@typescript-eslint/no-unused-vars": "off",
  "@typescript-eslint/ban-ts-comment": "error",
  "@typescript-eslint/no-unsafe-declaration-merging": "off",
  "@typescript-eslint/no-non-null-assertion": "off",

  // JSDoc — mostly relaxed; we don't fully doc everything.
  "jsdoc/check-access": "warn",
  "jsdoc/check-alignment": "warn",
  "jsdoc/check-param-names": "warn",
  "jsdoc/check-property-names": "warn",
  "jsdoc/check-tag-names": ["warn", { definedTags: ["category"] }],
  "jsdoc/check-types": "warn",
  "jsdoc/check-values": "warn",
  "jsdoc/empty-tags": "warn",
  "jsdoc/implements-on-classes": "warn",
  "jsdoc/no-bad-blocks": "warn",
  "jsdoc/require-description": "off",
  "jsdoc/require-jsdoc": "off",
  "jsdoc/require-param": "off",
  "jsdoc/require-param-name": "warn",
  "jsdoc/require-param-type": "off",
  "jsdoc/require-property": "warn",
  "jsdoc/require-property-name": "warn",
  "jsdoc/require-property-type": "off",
  "jsdoc/require-returns": "off",
  "jsdoc/require-returns-check": "off",
  "jsdoc/require-returns-type": "off",
  "jsdoc/require-yields-check": "warn",
  "jsdoc/valid-types": "off",
};

export default [
  {
    ignores: [
      ".github/**",
      "dist/**",
      "docs/**",
      "external/**",
      "src/languages/**",
      "src/assets/**",
      "src/lang/**",
      "src/styles/**",
      "src/templates/**",
      "src/**/*.svelte",
      "coverage/**",
      "node_modules/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jquery,
        ...foundryGlobals,
      },
    },
    plugins: { jsdoc, prettier },
    settings: {
      jsdoc: {
        preferredTypes: {
          ".<>": "<>",
          object: "Object",
          Object: "object",
        },
        mode: "typescript",
        tagNamePreference: { augments: "extends" },
      },
    },
    rules: sharedRules,
  },
  eslintConfigPrettier,
  // tests-specific overrides
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        beforeEach: "readonly",
        afterAll: "readonly",
        afterEach: "readonly",
        vi: "readonly",
      },
    },
    rules: {
      "global-require": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "no-undef": "off",
    },
  },
];
